config/routes.rb
CommunityApp::Application.routes.draw do
  mount CommunityEngine::Engine => "/"

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_filter :authenticate
  
  protect_from_forgery
  
    def authenticate
      authenticate_or_request_with_http_basic do |username, password|
        username == "rm" && password == "shocker"
      end
    end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "My Application" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Learn Rails" %>">
    <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>

    <div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <%= link_to "Community", community_engine_url, class: "brand" %>
          <div class="nav-collapse pull-right">
            <ul class="nav">
              <% if current_user.present? %>
                <li><%= link_to "Logout", logout_url %></li>
                <% else %>
                <li><%= link_to "Login", login_url %></li>
                <li><%= link_to "Sign Up", signup_url %></li>
                
                <% end %>
            </ul>
          </div>
        </div>
      </div>
    </div>


    <div class="container" style="margin-top:30px;">
      <div class="row">
        <div class="span9"><%= yield %></div>
      </div>
    </div>
  </body>
</html>